"""HTTP target adapter and response detectors.

Attack payloads are never generated by this module. The LLM-backed Attacker
agent creates one payload per branch and this package only executes HTTP and
collects deterministic detector signals for the Evaluator.
"""

from cyberredteam.tools.target_adapter import HttpTargetAdapter, TargetAdapter
from cyberredteam.tools.prompt_injection import PromptInjectionTool, analyze_prompt_injection_response
from cyberredteam.tools.tool_abuse import ToolAbuseTool, detect_tool_misuse
from cyberredteam.tools.memory_poisoning import MemoryPoisoningTool, check_memory_poisoning
from cyberredteam.tools.sensitive_data import (
    SensitiveDataExtractor, scan_response_for_sensitive_data, check_canary_token_exfiltration,
)
from cyberredteam.tools.rag_probe import RAGProbeTool, analyze_rag_retrieval_response
from cyberredteam.tools.jailbreak import JailbreakTool, check_jailbreak_response
from cyberredteam.tools.instruction_hierarchy import InstructionHierarchyTool, check_hijack_response
from cyberredteam.tools.workflow_manipulation import WorkflowManipulationTool, check_dos_response

ALL_RED_TEAM_TOOLS = [
    analyze_prompt_injection_response, detect_tool_misuse, check_memory_poisoning,
    scan_response_for_sensitive_data, check_canary_token_exfiltration,
    analyze_rag_retrieval_response, check_jailbreak_response, check_hijack_response,
    check_dos_response,
]

__all__ = [
    "TargetAdapter", "HttpTargetAdapter", "PromptInjectionTool", "ToolAbuseTool",
    "MemoryPoisoningTool", "SensitiveDataExtractor", "RAGProbeTool", "JailbreakTool",
    "InstructionHierarchyTool", "WorkflowManipulationTool", "analyze_prompt_injection_response",
    "detect_tool_misuse", "check_memory_poisoning", "scan_response_for_sensitive_data",
    "check_canary_token_exfiltration", "analyze_rag_retrieval_response",
    "check_jailbreak_response", "check_hijack_response", "check_dos_response",
    "ALL_RED_TEAM_TOOLS",
]
